CREATE DATABASE UF2_EJS;

CREATE TABLE TREBALL (
nom 	VARCHAR(20)	PRIMARY KEY,
edad	INTEGER	,
carrec	VARCHAR(50)
);

CREATE TABLE CIUTAT (
nom		VARCHAR(25)		PRIMARY KEY,
comarca	VARCHAR(25)		NOT NULL,
provincia	VARCHAR(25)	NOT NULL,
habitants	INTEGER
);

CREATE TABLE CLIENTE(
idclient	INTEGER AUTO_INCREMENT,	
nom		CHAR(20)	UNIQUE,
cognoms	CHAR(20)	UNIQUE,
datanaixement	DATE,
tipus 	TEXT 	DEFAULT(Habitual)
);

CREATE TABLE DEPARTAMENT(
num		TINYINT(2),
nom 	VARCHAR(9),
localitzacio	VARCHAR(10)
);

CREATE TABLE DEPARTAMENT2(
num		TINYINT(2) PRIMARY KEY,
nom 	VARCHAR(9),
localitzacio	VARCHAR(10)
);
